on:
  push:
    paths-ignore:
      - 'README.md' # Specify the path to your README file

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: CheckCode
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push and build to DockerHub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: donkevlar/DockerBot:latest, donkevlar/DockerBot:${{ github.run_number }}
